'use client';
import './globals.css';
import localFont from 'next/font/local';
import { ThemeProvider } from '@/components/theme-provider';
import Header from '@/components/layouts/Header';
import { MessageProvider } from '@/context/MessageContext';
import { ClerkProvider } from '@clerk/nextjs';
import ConvexClientProvider from './ConvexClientProvider';

import { UserDetailProvider } from './context/UserDetailContext'; // Sử dụng đường dẫn tương đối
import { useState } from 'react';
import { ActionContext } from '@/context/ActionContext';

const beVietnamPro = localFont({
  src: [
    {
      path: './fonts/BeVietnamPro-Bold.ttf',
      weight: '700',
    },
    {
      path: './fonts/BeVietnamPro-Medium.ttf',
      weight: '500',
    },
    {
      path: './fonts/BeVietnamPro-Regular.ttf',
      weight: '400',
    },
  ],
});
// export const metadata = {
//   title: 'Create Next App',
//   description: 'Generated by create next app',
// };

export default function RootLayout({ children }) {
  const [action, setAction] = useState();
  return (

    <ClerkProvider dynamic afterSignOutUrl="/">
      <html lang="en" suppressHydrationWarning>
        <body className={`${beVietnamPro.className} antialiased`}>
          
          <ActionContext.Provider value={{ action, setAction }}>
            <ThemeProvider
              attribute="class"
              defaultTheme="light"
              enableSystem
              disableTransitionOnChange
            >
              {/*Đặt ConvexClientProvider trước UserDetailProvider */}
              <ConvexClientProvider>
                <UserDetailProvider>{children}</UserDetailProvider>
              </ConvexClientProvider>
            </ThemeProvider>
          </ActionContext.Provider>
        </body>
      </html>
    </ClerkProvider >
  );
}
